[[java-juc]]
= Java 并发

[[guide-juc-1]]
== 同步和异步，阻塞和非阻塞

* 同步：调用者要一直等待调用结果的通知后才能进行后续的执行，现在就要，我可以等，等处结果为止
* 异步：指被调用者先返回应答让调用者先回去，然后在计算调用结果，计算完结果后再通知并返回给调用者。异步调用一般想要获得结果一般通过回调。
* 阻塞：调用方一直在等待而且不做任何事，当前进程/线程会被挂起，啥都不干
* 非阻塞：调用在发出去后，调用方先去忙别的事情，不会阻塞当前进程/线程，而会立即返回

同步，异步讨论的对象一般是被调用者（服务提供者），重点在于获得调用结果的消息的通知方式上。
阻塞，非阻塞讨论的对象一般是调用者（服务请求者），重点在于等消息时候的行为，调用者是否能干其他事。

[[guide-juc-2]]
== 公平锁/非公平锁/可重入锁/独占锁/共享锁自旋锁

=== 公平锁/非公平锁

公平锁:是指多个线程按照申请锁的顺序来获取锁,类似于排队打饭,先来后到.

非公平锁:是指多个线程取锁的顺序并不是按照申请锁的顺序,有可能后申请的线程比先申请的线程先获得锁,在高并发的情况下,有可能会造成优先级反转或者饥饿现象.

区别:

* 并发包中的 ReentrantLock 的创建可以指定构造函数的 Boolean 类型来得到公平锁或非公平锁,默认非公平锁
* 公平锁:就是很公平,在并发环境中,每个线程在获取锁时会先查看此锁维护的等待队列,如果为空,或者当前线程是等待队列的第一个,就占有锁,否则就是加入到等待队列中,以后会按照 FIFO 的规则从队列中取到自己.
* 非公平锁:非公平锁比较粗鲁,上来就直接尝试占有锁,如果尝试失败,就采用类似公平锁那种方式.
* 非公平锁的有点在于吞吐量比公平锁大.
* 对于 Synchronized 而言,也是一种非公平锁.

=== 可重入锁

可重入锁(递归锁):如果当前线程已经获得了某个监视器对象所持有的锁,那么该线程在该方法中调用另外一个同步方法也同样持有该锁.

[source,java]
----
public synchrnozied void test() {
    xxxxxx;
    test2();
}

public synchronized void test2() {
    yyyyy;
}
----

在上面代码段中,执行 `test` 方法需要获得当前对象作为监视器的对象锁,但方法中又调用了 `test2` 的同步方法.

如果锁是具有可重入性的话,那么该线程在调用 `test2` 时并不需要再次获得当前对象的锁,可以直接进入 `test2` 方法进行操作.

如果锁是不具有可重入性的话,那么该线程在调用 `test2` 前会等待当前对象锁的释放,实际上该对象锁已被当前线程所持有,不可能再次获得.

如果锁是不具有可重入性特点的话,那么线程在调用同步方法、含有锁的方法时就会产生死锁.

=== 自旋锁(spinlock)

是指尝试获取锁的线程不会立即阻塞,而是采用循环的方式尝试获取锁.这样的好处是减少线程上下文切换的消耗,缺点是循环会消耗 CPU.

手写自旋锁.查看代码 SpinLockDemo

=== 独占锁(写锁)/共享锁(读锁)/互斥锁

独占锁:指该锁一次只能被一个线程持有.对 `ReentrantLock` 和 `Synchronized` 而言都是独占锁

共享锁:指该锁可被多个线程持有,对 `ReentrantReadWriteLock` 其读锁是共享锁,其写锁是独占锁

互斥锁:

读锁的共享锁可保证并发读是非常高效的,读写,写读,写写的过程是互斥的.

[[guide-juc-3]]
== 当一个线程进入一个对象的 synchronized 方法 A 之后,其它线程是否可进入此对象的 synchronized 方法  B？

不能.其它线程只能访问该对象的非同步方法,同步方法则不能进入.因为非静态方法上的 `synchronized` 修饰符要求执行方法时要获得对象的锁,如果已经进入 A 方法说明对象锁已经被取走,那么试图进入 B 方法的线程就只能在等锁池(注意不是等待池哦)中等待对象的锁.

[[guide-juc-4]]
== synchronized 关键字的用法？

`synchronized` 关键字可以将对象或者方法标记为同步,以实现对对象和方法的互斥访问,可以用 `synchronized(对象) { … }` 定义同步代码块，
或者在声明方法时将 `synchronized` 作为方法的修饰符.在上面的例子中已经展示了 `synchronized` 关键字的用法.

[[guide-juc-15]]
== 简述 synchronized 和 java.util.concurrent.locks.Lock 的底层原理？

=== Synchronized 原理：

方法级的同步是隐式，即无需通过字节码指令来控制的，它实现在方法调用和返回操作之中。JVM 可以从方法常量
池中的方法表结构(method_info Structure) 中的 ACC_SYNCHRONIZED 访问标志区分一个方法是否同步方法。当
方法调用时，调用指令将会 检查方法的 ACC_SYNCHRONIZED 访问标志是否被设置，如果设置了，执行线程将
先持有 monitor（虚拟机规范中用的是管程一词）， 然后再执行方法，最后再方法完成(无论是正常完成还是非正常
完成)时释放 monitor。

代码块的同步是利用 monitorenter 和 monitorexit 这两个字节码指令。它们分别位于同步代码块的开始和结束位置。
当 jvm 执行到 monitorenter 指令时，当前线程试图获取 monitor 对象的所有权，如果未加锁或者已经被当前线程所
持有，就把锁的计数器+1；当执行 monitorexit 指令时，锁计数器-1；当锁计数器为 0 时，该锁就被释放了。如果获
取 monitor 对象失败，该线程则会进入阻塞状态，直到其他线程释放锁。

=== Lock 原理：

Lock 的存储结构：一个 int 类型状态值（用于锁的状态变更），一个双向链表（用于存储等待中的线程）

Lock 获取锁的过程：本质上是通过 CAS 来获取状态值修改，如果当场没获取到，会将该线程放在线程等待链
表中。

Lock 释放锁的过程：修改状态值，调整等待链表。

Lock 大量使用 CAS+自旋。因此根据 CAS 特性，lock 建议使用在低锁冲突的情况下。

[[guide-juc-5]]
== 简述 synchronized 和 java.util.concurrent.locks.Lock 的异同？

Lock 是 Java 5 以后引入的新的 API,和关键字 synchronized 相比主要相同点:Lock 能完成 synchronized 所实现的所有功能

|===
|区别 | synchronized | Lock

| 语法
| Synchronized 是 Java 的关键字，可以直接应用于方法或代码块中。
| Lock 是一个接口，需要实例化一个 Lock 对象，并使用 lock() 和 unlock() 方法来手动控制同步。

| 锁的释放
| 1、以获取锁的线程执行完同步代码，释放锁 2、线程执行发生异常，jvm 会让线程释放锁
| 在 finally 中必须释放锁，不然容易造成线程死锁

| 锁的释放（死锁产生）
| 在发生异常时候会自动释放占有的锁，因此不会出现死锁
| 发生异常时候，不会主动释放占有的锁，必须手动 unlock 来释放锁，可能引起死锁的发生

| 锁的获取
| 假设 A 线程获得锁，B 线程等待。如果 A 线程阻塞，B 线程会一直等待
| 分情况而定，Lock 有多个锁获取的方式，大致就是可以尝试获得锁，线程可以不用一直等待(可以通过 `tryLock` 判断有没有锁)

| 锁的状态
| 无法判断
| 可以判断(tryLock() ,getHoldCount(),isHeldByCurrentThread())

| 锁的类型
| 可重入(即同一个线程可以重复获取同一把锁) 不可中断 非公平
| 可重入 可判断( `lockInterruptibly()` ) 可公平（两者皆可）

| 性能
| 少量同步
| 大量同步。Lock 可以提高多个线程进行读操作的效率。（可以通过 ReadWriteLock 实现读写分离）。
在资源竞争不是很激烈的情况下，Synchronized 的性能要优于 ReentrantLock，但是在资源竞争很激烈的情况下，Synchronized 的性能会下降几十倍，但是 ReentrantLock 的性能能维持常态；
ReentrantLock 提供了多样化的同步，比如有时间限制的同步，可以被 Interrupt 的同步（synchronized 的同步是不能 Interrupt 的）等。在资源竞争不激烈的情形下，性能稍微比 synchronized 差点点。
但是当同步非常激烈的时候，synchronized 的性能一下子能下降好几十倍。而 ReentrantLock 确还能维持常态。


| 调度
| 使用 Object 对象本身的 wait 、notify、notifyAll 调度机制
| 可以使用 Condition 进行线程之间的调度

| 用法
| 在需要同步的对象中加入此控制，synchronized 可以加在方法上，也可以加在特定代码块中，括号中表示需要锁的对象。
| 一般使用 ReentrantLock 类做为锁。在加锁和解锁处需要通过 `lock()` 和 `unlock()` 显示指出。所以一般会在 finally 块中写 `unlock()` 以防死锁。

| 锁升级
| 有
| 无

| 锁对象
| 锁是一个对象,并且锁的信息保存在了对象中
| 代码中通过 int 类型的 state 标识

| 底层实现
| 底层使用指令码方式来控制锁的，映射成字节码指令就是增加来两个指令：`monitorenter` 和 `monitorexit`。当线程执行遇到 `monitorenter` 指令时会尝试获取内置锁，如果获取锁则锁计数器+1，如果没有获取锁则阻塞；当遇到 `monitorexit` 指令时锁计数器 `-1`，如果计数器为 0 则释放锁。
| 底层是 CAS 乐观锁，依赖 `AbstractQueuedSynchronizer` 类，把所有的请求线程构成一个 CLH 队列。而对该队列的操作均通过 Lock-Free（CAS）操作。
|===

Lock 有比 `synchronized` 更精确的线程语义和更好的性能,而且不强制性的要求一定要获得锁.`synchronized` 会自动释放锁,而 Lock 一定要求程序员手工释放,并且最好在 `finally` 块中释放(这是释放外部资源的最好的地方).


[[guide-juc-6]]
== volatile 关键字？

https://study.jcohy.com/java/htmlsingle/index.html#java-juc-volatile[Volatile]

[[guide-juc-7]]
==  volatile 变量和 atomic 变量有什么不同

volatile 变量和 `atomic` 变量看起来很像,但功能却不一样.volatile 变量可以确保先行关系,即写操作会发生在后续的读操作之前, 但它并不能保证原子性.例如用 `volatile` 修饰 count 变量那么 `count++` 操作并不是原子性的.而 `AtomicInteger` 类提供的 atomic 方法可以让这种操作具有原子性如 `getAndIncrement()` 方法会原子性的进行增量操作把当前值加一,其它数据类型和引用变量也可以进行相似操作.

[[guide-juc-8]]
== JDK 提供的用于并发编程的同步器

. `Semaphore` Java 并发库的 Semaphore 可以很轻松完成信号量控制,`Semaphore` 可以控制某个资源可被同时访问的个数,通过 `acquire()` 获取一个许可,如果没有就等待,而 `release()` 释放一个许可.
. `CyclicBarrier` 主要的方法就是一个:await().await() 方法每被调用一次,计数便会减少 1,并阻塞住当前线程.当计数减至 0 时,阻塞解除,所有在此 `CyclicBarrier` 上面阻塞的线程开始运行.
. `CountDownLatch` 直译过来就是倒计数(CountDown)门闩(Latch).倒计数不用说,门闩的意思顾名思义就是阻止前进.在这里就是指 `CountDownLatch.await()` 方法在倒计数为 0 之前会阻塞当前线程.

详情可查看 https://study.jcohy.com/java/htmlsingle/index.html#java-juc[https://study.jcohy.com/java/htmlsingle/index.html#java-juc]

[[guide-juc-9]]
== Java 中 CyclicBarrier 和 CountDownLatch 有什么不同

它们都是 JUC 下的类,`CyclicBarrier` 和 `CountDownLatch` 都可以用来让一组线程等待其它线程。
区别在于 `CountdownLatch` 计数无法被重置.如果需要重置计数,请考虑使用 `CyclicBarrier`.

[[guide-juc-10]]
== Java 中 Semaphore 是什么

JUC 下的一种新的同步类,它是一个计数信号.从概念上讲,Semaphore 信号量维护了一个许可集合.如有必要,在许可可用前会阻塞每一个 `acquire`,然后再获取该许可.
每个 release 添加一个许可,从而可能释放一个正在阻塞的获取者.但是,不使用实际的许可对象,Semaphore 只对可用许可的号码进行计数,并采取相应的行动.
信号量常常用于多线程的代码中,比如数据库连接池.

[[guide-juc-11]]
== Java 中的 ReadWriteLock 是什么？

一般而言,读写锁是用来提升并发程序性能的锁分离技术的成果.Java 中的 ReadWriteLock 是 Java 5 中新增的一个接口,一个 ReadWriteLock 维护一对关联的锁,一个用于只读操作一个用于写.
在没有写线程的情况下一个读锁可能会同时被多个读线程持有.写锁是独占的,你可以使用 JDK 中的 `ReentrantReadWriteLock` 来实现这个规则,它最多支持 65535 个写锁和 65535 个读锁.

[[guide-juc-12]]
== 什么是 FutureTask？

在 Java 并发程序中 `FutureTask` 表示一个可以取消的异步运算.它有启动和取消运算、查询运算是否完成和取回运算结果等方法.只有当运算完成的时候结果才能取回,如果运算尚未完成 get 方法将会阻塞.
一个 `FutureTask` 对象可以对调用了 `Callable` 和 `Runnable` 的对象进行包装,由于 `FutureTask` 也是调用了 `Runnable` 接口所以它可以提交给 `Executor` 来执行.

[[guide-juc-13]]
== Java 中的同步集合与并发集合有什么区别

同步集合与并发集合都为多线程和并发提供了合适的线程安全的集合，不过并发集合的可扩展性更高。
在 Java1.5 之前程序员们只有同步集合来用且在多线程并发的时候会导致争用,阻碍了系统的扩展性。

Java1.5 加入了并发集合像 `ConcurrentHashMap`,不仅提供线程安全还用锁分离和内部分区等现代技术提高了可扩展性.它们大部分位于 JUC 包下.

[[guide-juc-14]]
== 常见线程安全的并发容器有哪些？

CopyOnWriteArrayList、CopyOnWriteArraySet、ConcurrentHashMap
CopyOnWriteArrayList、CopyOnWriteArraySet 采用写时复制实现线程安全。

ConcurrentHashMap 采用分段锁的方式实现线程安全

[[guide-juc-16]]
== Atomic 原子类了解多少？原理是什么？

Java 的原子类都存放在并发包 java.util.concurrent.atomic 下：

* 基本类型
** 使用原子的方式更新基本类型
** AtomicInteger：整形原子类
** AtomicLong：长整型原子类
** AtomicBoolean：布尔型原子类
* 数组类型：使用原子的方式更新数组里的某个元素
** AtomicIntegerArray：整形数组原子类
** AtomicLongArray：长整形数组原子类
** AtomicReferenceArray：引用类型数组原子类
* 引用类型
** AtomicReference：引用类型原子类
** AtomicStampedReference：原子更新引用类型里的字段原子类
** AtomicMarkableReference ：原子更新带有标记位的引用类型
** 对象的属性修改类型
** AtomicIntegerFieldUpdater：原子更新整形字段的更新器
** AtomicLongFieldUpdater：原子更新长整形字段的更新器
** AtomicStampedReference：原子更新带有版本号的引用类型。该类将整数值与引用关联起来，可用于解决原
子的更新数据和数据的版本号，以及解决使用 CAS 进行原子更新时可能出现的 ABA 问题。

AtomicInteger 类利用 CAS (Compare and Swap) + volatile + native 方法来保证原子操作，从而避免 synchronized 的
高开销，执行效率大为提升。

CAS 的原理，是拿期望值和原本的值作比较，如果相同，则更新成新的值。UnSafe 类的 objectFieldOffset() 方法
是个本地方法，这个方法是用来拿 "原值" 的内存地址，返回值是 valueOffset；另外，value 是一个 volatile 变量，
因此 JVM 总是可以保证任意时刻的任何线程总能拿到该变量的最新值。

[[guide-juc-17]]
== 了解 ConcurrentHashMap 吗?为什么性能比HashTable 高，说下原理

ConcurrentHashMap 是线程安全的 Map 容器，JDK8 之前，ConcurrentHashMap 使用锁分段技术，将数据分成一段段
存储，每个数据段配置一把锁，即 segment 类，这个类继承 ReentrantLock 来保证线程安全， JKD8 的版本取消 Segment
这个分段锁数据结构，底层也是使用 Node 数组+链表+红黑树，从而实现对每一段数据就行加锁，也减少了并发冲
突的概率。
hashtable 类基本上所有的方法都是采用 synchronized 进行线程安全控制，高并发情况下效率就降低 ，
ConcurrentHashMap 是采用了分段锁的思想提高性能，锁粒度更细化

[[guide-juc-18]]
== synchronized 和 volatile 有什么区别？

. volatile 本质是告诉 JVM 当前变量在寄存器中的值是不确定的，需要从主存中读取，synchronized 则是锁定当前变
量，只有当前线程可以访问该变量，其他线程被阻塞住。
. volatile 仅能用在变量级别，而 synchronized 可以使用在变量、方法、类级别。
. volatile 仅能实现变量的修改可见性，不能保证原子性；而 synchronized 则可以保证变量的修改可见性和原子性。
. volatile 不会造成线程阻塞，synchronized 可能会造成线程阻塞。
. volatile 标记的变量不会被编译器优化，synchronized 标记的变量可以被编译器优化。