[[web-optimize]]
= 优化

[[web-optimize-1]]
== 大型网站在架构上应当考虑哪些问题？

* 分层:分层是处理任何复杂系统最常见的手段之一,将系统横向切分成若干个层面,每个层面只承担单一的职责,然后通过下层为上层提供的基础设施和服务以及上层对下层的调用来
形成一个完整的复杂的系统.计算机网络的开放系统互联参考模型(OSI/RM)和 Internet 的 TCP/IP 模型都是分层结构,大型网站的软件系统也可以
使用分层的理念将其分为持久层(提供数据存储和访问服务)、业务层(处理业务逻辑,系统中最核心的部分)和表示层(系统交互、视图展示).需要指出的是:
(1)分层是逻辑上的划分,在物理上可以位于同一设备上也可以在不同的设备上部署不同的功能模块,这样可以使用更多的计算资源来应对用户的并发访问;
(2)层与层之间应当有清晰的边界,这样分层才有意义,才更利于软件的开发和维护.
* 分割:分割是对软件的纵向切分.我们可以将大型网站的不同功能和服务分割开,形成高内
聚低耦合的功能模块(单元).在设计初期可以做一个粗粒度的分割,将网站分割为若干个功能模块,后期还可以进一步对每个模块进行细粒度的分割,这样一方面有助于软
件的开发和维护,另一方面有助于分布式的部署,提供网站的并发处理能力和功能的扩展.
* 分布式:除了上面提到的内容,网站的静态资源(JavaScript、CSS、图片等)也可以采用独立分布式部署并采用独立的域名,这样可
以减轻应用服务器的负载压力,也使得浏览器对资源的加载更快.数据的存取也应该是分布式的,传统的商业级关系型数据库产品基本上都支持分布式部署,而新生的 NoSQL 产品
几乎都是分布式的.当然,网站后台的业务处理也要使用分布式技术,例如查询索引的构建、数据分析等,这些业务计算规模庞大,可以使用 Hadoop 以及 MapReduce 分布式计算框架来处理.
* 集群:集群使得有更多的服务器提供相同的服务,可以更好的提供对并发的支持.
* 缓存:所谓缓存就是用空间换取时间的技术,将数据尽可能放在距离计算最近的位置.使用缓存是网站优化的第一定律.我们通常说的 CDN、反向代理、热点数据都是对缓存技术的使用.
* 异步:异步是实现软件实体之间解耦合的又一重要手段.异步架构是典型的生产者消费者模式,二者之间没有直接的调用关系,只要保持数据结构不变,彼此功能实现可以随意
变化而不互相影响,这对网站的扩展非常有利.使用异步处理还可以提高系统可用性,加快网站的响应速度(用 Ajax 加载数据就是一种异步技术),同时还可以起到削
峰作用(应对瞬时高并发).&quot;能推迟处理的都要推迟处理"是网站优化的第二定律,而异步是践行网站优化第二定律的重要手段.
* 冗余:各种服务器都要提供相应的冗余服务器以便在某台或某些服务器宕机时还能保证网站可以正常工作,同时也提供了灾难恢复的可能性.冗余是网站高可用性的重要保证.

[[web-optimize-2]]
== 你用过的网站前端优化的技术有哪些？

. 浏览器访问优化:
* 减少 HTTP 请求数量:合并 CSS、合并 JavaScript、合并图片(CSS Sprite)
* 使用浏览器缓存:通过设置 HTTP 响应头中的 `Cache-Control` 和 `Expires` 属性,将 CSS、JavaScript、图片等在浏览器中缓存,当这些静态资源需要更新时,可以更新 HTML 文件中的引用来
让浏览器重新请求新的资源
* 启用压缩
* CSS前置,JavaScript 后置
* 减少 Cookie 传输
. CDN 加速:CDN(Content Distribute Network)的本质仍然是缓存,将数据缓存在离用户最近的地方,CDN通常部署在网络运营商的机房,不仅可以提升
响应速度,还可以减少应用服务器的压力.当然,CDN 缓存的通常都是静态资源.
. 反向代理:反向代理相当于应用服务器的一个门面,可以保护网站的安全性,也可以实现负载均衡的功能,当然最重要的是它缓存了用户访问的热点资源,可以直接从反向
代理将某些内容返回给用户浏览器.

[[web-optimize-3]]
== 你使用过的应用服务器优化技术有哪些？

. 分布式缓存:缓存的本质就是内存中的哈希表,如果设计一个优质的哈希函数,那么理论上哈希表读写的渐近时间复杂度为 `O(1)`.缓存主要用来存放那些读写比很高、变化很少的数据,这样应用程序读取数据时先到
缓存中读取,如果没有或者数据已经失效再去访问数据库或文件系统,并根据拟定的规则将数据写入缓存.对网站数据的访问也符合二八定律(Pareto分布,幂律分布),即 80% 的访问都
集中在 20% 的数据上,如果能够将这 20% 的数据缓存起来,那么系统的性能将得到显著的改善.当然,使用缓存需要解决以下几个问题:
* 频繁修改的数据;
* 数据不一致与脏读;
* 缓存雪崩(可以采用分布式缓存服务器集群加以解决,memcached 是广泛采用的解决方案);
* 缓存预热;
* 缓存穿透(恶意持续请求不存在的数据).
. 异步操作:可以使用消息队列将调用异步化,通过异步处理将短时间高并发产生的事件消息存储在消息队列中,从而起到削峰作用.电商网站在进行促销活动时,可以将用
户的订单请求存入消息队列,这样可以抵御大量的并发订单请求对系统和数据库的冲击.目前,绝大多数的电商网站即便不进行促销活动,订单系统都采用了消息队列来处理.
. 使用集群.
. 代码优化:
* 多线程:基于Java的Web开发基本上都通过多线程的方式响应用户的并发请求,使用多线程技术在编程上要解决线程安全问题,主要可以考虑以下几个方面:
* 将对象设计为无状态对象(这和面向对象的编程观点是矛盾的,在面向对象的世界中被视为不良设计),这样就不会存在并发访问时对象状态不一致的问题.
* 在方法内部创建对象,这样对象由进入方法的线程创建,不会出现多个线程访问同一对象的问题.使用 `ThreadLocal` 将对象与线程绑定也是很好的做法,这一点在前面已经探讨过了.
* 对资源进行并发访问时应当使用合理的锁机制.
* 非阻塞I/O:使用单线程和非阻塞I/O是目前公认的比多线程的方式更能充分发挥服务器性能的应用模式,基于 Node.js 构建的服务器就采用了这样的方式.Java 在 JDK 1.4 中
就引入了 NIO(Non-blocking I/O),在 Servlet 3 规范中又引入了异步 Servlet 的概念,这些都为在服务器端采用非阻塞 I/O 提供了必要的基础.
* 资源复用:资源复用主要有两种方式,一是单例,二是对象池,我们使用的数据库连接池、线程池都是对象池化技术,这是典型的用空间换取时间的策略,另一方面也实现对资源的复
用,从而避免了不必要的创建和释放资源所带来的开销.