[[web-security]]
= 安全

[[web-security-1]]
== 什么是 XSS 攻击？什么是 SQL 注入攻击？什么是 CSRF 攻击？

* XSS(Cross Site Script,跨站脚本攻击)是向网页中注入恶意脚本在用户浏览网页时在用户浏览器中执行恶意脚本的攻击方式.跨站脚本攻击分有两种形式:反射型攻
击(诱使用户点击一个嵌入恶意脚本的链接以达到攻击的目标,目前有很多攻击者利用论坛、微博发布含有恶意脚本的 URL 就属于这种方式)和持久型攻
击(将恶意脚本提交到被攻击网站的数据库中,用户浏览网页时,恶意脚本从数据库中被加载到页面执行,QQ 邮箱的早期版本就曾经被利用作为持久型跨站脚本攻击的平台).XSS 虽
然不是什么新鲜玩意,但是攻击的手法却不断翻新,防范 XSS 主要有两方面:消毒(对危险字符进行转义)和 HttpOnly(防范 XSS 攻击者窃取 Cookie 数据).
* SQL 注入攻击是注入攻击最常见的形式(此外还有 OS 注入攻击(Struts 2 的高危漏洞就是通过 OGNL 实施 OS 注入攻击导致的)),当服务器使用请求参数构造 SQL 语句时,恶
意的 SQL 被嵌入到 SQL 中交给数据库执行.SQL 注入攻击需要攻击者对数据库结构有所了解才能进行,攻击者想要获得表结构有多种方式:
. 如果使用开源系统搭建网站,数据库结构也是公开的(目前有很多现成的系统可以直接搭建论坛,电商网站,虽然方便快捷但是风险是必须要认真评估的);
. 错误回显(如果将服务器的错误信息直接显示在页面上,攻击者可以通过非法参数引发页面错误从而通过错误信息了解数据库结构,Web 应用应当设
置友好的错误页,一方面符合最小惊讶原则,一方面屏蔽掉可能给系统带来危险的错误回显信息);
. 盲注.防范 SQL 注入攻击也可以采用消毒的方式,通过正则表达式对请求参数进行验证,此外,参数绑定也是很好的手段,这样恶意的 SQL 会被当做 SQL 的参数而不
是命令被执行,JDBC 中的 `PreparedStatement` 就是支持参数绑定的语句对象,从性能和安全性上都明显优于 `Statement`.
* CSRF 攻击(Cross Site Request Forgery,跨站请求伪造)是攻击者通过跨站请求,以合法的用户身份进行非法操作(如转账或发帖等).CSRF 的原理是利用
浏览器的 Cookie 或服务器的 Session,盗取用户身份,其原理如下图所示.防范 CSRF 的主要手段是识别请求者的身份,主要有以下几种方式:
. 在表单中添加令牌(token);
. 验证码;
. 检查请求头中的 Referer(前面提到防图片盗链接也是用的这种方式).令牌和验证都具有一次消费性的特征,因此在原理上一致的,但是验证码是一种糟糕的用户体验,不是必要的情况下不要轻易使用验证码,目前很多网站的做法是如果在短时间内多次提交一个表单未获得成功后才要求提供验证码,这样会获得较好的用户体验.

{oss-images}/guide-6.jpg[]

补充:防火墙的架设是 Web 安全的重要保障,ModSecurity 是开源的 Web 防火墙中的佼佼者.企业级防火墙的架设应当有两级防火墙,Web 服务器和部分应用服务器可以架设在两级防火墙之间的 DMZ,而数据和资源服务器应当架设在第二级防火墙之后.