[[web-xml]]
= XML

[[web-xml-1]]
== XML 文档定义有几种形式？它们之间有何本质区别？解析XML文档有哪几种方式？

XML 文档定义分为 DTD 和 Schema 两种形式,二者都是对 XML 语法的约束,其本质区别在于 Schema 本身也是一个 XML 文件，可以被 XML 解析器解析，而且可以为 XML 承载的数据定义类型，约束能力较之 DTD 更强大。
对 XML 的解析主要有 DOM(文档对象模型,Document Object Model)、SAX(Simple API for XML)和 StAX(Java 6 中引入的新的解析 XML 的方式,Streaming API for XML)，
其中 DOM 处理大型文件时其性能下降的非常厉害,这个问题是由 DOM 树结构占用的内存较多造成的,而且 DOM 解析方式必须在解析文件之前把整个文档装入内存，
适合对 XML 的随机访问(典型的用空间换取时间的策略);SAX 是事件驱动型的 XML 解析方式,它顺序读取 XML 文件,不需要一次全部装载整个文件。
当遇到像文件开头，文档结束，或者标签开头与标签结束时，它会触发一个事件,用户通过事件回调代码来处理 XML 文件,适合对 XML 的顺序访问。
顾名思义,StAX 把重点放在流上,实际上 StAX 与其他解析方式的本质区别就在于应用程序能够把 XML 作为一个事件流来处理。
将 XML 作为一组事件来处理的想法并不新颖(SAX 就是这样做的),但不同之处在于 StAX 允许应用程序代码把这些事件逐个拉出来,而不用提供在解析器方便时从解析器中接收事件的处理程序。

[[web-xml-2]]
== 你在项目中哪些地方用到了 XML？


XML 的主要作用有两个方面:数据交换和信息配置.在做数据交换时,XML 将数据用标签组装成起来,然后压缩打包加密后通过网络传送给接收者,接收解密与解压缩后再从 XML 文件中还原相关信息进行处理.

XML 曾经是异构系统间交换数据的事实标准,但此项功能几乎已经被 JSON(JavaScript Object Notation)取而代之.当然,目前很多软件仍然使用XML来存储配置信息,我们在很多项目中通常也会将作为配置信息的硬代码写在 XML 文件中，Java 的很多框架也是这么做的,而且这些框架都选择了 dom4j 作为处理 XML 的工具，
因为 Sun 公司的官方 API 实在不怎么好用.

补充:现在有很多时髦的软件(如 Sublime)已经开始将配置文件书写成 JSON 格式,我们已经强烈的感受到 XML 的另一项功能也将逐渐被业界抛弃。

[[web-xml-3]]
== XML 与 JSON 对比和区别

XML

. 应用广泛,可扩展性强,被广泛应用各种场合
. 读取、解析没有JSON快
. 可读性强,可描述复杂结构

JSON

. 结构简单,都是键值对
. 读取、解析速度快,很多语言支持
. 传输数据量小,传输速率大大提高
. 描述复杂结构能力较弱

JavaScript、PHP 等原生支持,简化了读取解析.成为当前互联网时代普遍应用的数据结构.